include:
  - component: $CI_SERVER_FQDN/oaklab/ci-templates/goreleaser-release@12
  - component: $CI_SERVER_FQDN/oaklab/ci-templates/goreleaser-test@12

stages:
  - test
  - release

variables:
  FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"
